name: test

on:
  push:
    paths:
      - 'Image2Display/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'Image2Display/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: environment prepare
        run: |
          winget install Microsoft.DotNet.Runtime.7
          winget install Microsoft.DotNet.SDK.6
      - name: test
        run: |
          cd Image2Display
          dotnet test
